#!/bin/sh

if [ -d "/usr/yi-hack-v3" ]; then
	mkdir /dev/pts
	mount -t devpts devpts /dev/pts

	udevd --daemon
	udevstart
	/usr/yi-hack-v3/script/system_init.sh
elif [ -d "/home/yi-hack-v3" ]; then
	mkdir /dev/pts
	mount -t devpts devpts /dev/pts

	mkdir -p /dev/.udev
	udevd --daemon
	udevadm trigger
	mount -t jffs2 /dev/mtdblock5 /home
	/home/yi-hack-v3/script/system_init.sh
	/home/base/init.sh
fi
